version: "3.9"

services:
  owlers-service:
    build:
      context: ./owlers-service
    container_name: owlers-service
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongodb:27017/owlers-db
      - VIRTUAL_HOST=rest.owlers.io
      - LETSENCRYPT_HOST=rest.owlers.io
      - LETSENCRYPT_EMAIL=owlersnest@gmail.com
    expose:
      - "3000"
    networks:
      - nginx_proxy
      - app-network
    depends_on:
      - mongodb
    restart: unless-stopped

  owlers-app:
    build:
      context: ./owlers-client
      args:
        VITE_API_URL: https://rest.owlers.io
    container_name: owlers-app
    environment:
      - NODE_ENV=production
      - VITE_API_BASE_URL=https://rest.owlers.io
      - VIRTUAL_HOST=dashboard.owlers.io
      - LETSENCRYPT_HOST=dashboard.owlers.io
      - LETSENCRYPT_EMAIL=owlersnest@gmail.com
    expose:
      - "80"
    depends_on:
      - owlers-service
    networks:
      - nginx_proxy
      - app-network
    restart: unless-stopped

  owlers-site:
    build:
      context: ./owlers-website
    container_name: owlers-site
    environment:
      - NODE_ENV=production
      - VIRTUAL_HOST=owlers.io
      - LETSENCRYPT_HOST=owlers.io
      - LETSENCRYPT_EMAIL=owlersnest@gmail.com

  mongodb:
    image: mongo:latest
    container_name: owlers-db
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network
    restart: unless-stopped

volumes:
  mongodb_data:

networks:
  nginx_proxy:
    external: true
  app-network:
