/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as erc20Sol from "./ERC20.sol";
export type { erc20Sol };
import type * as erc20MetaDataSol from "./ERC20MetaData.sol";
export type { erc20MetaDataSol };
import type * as mockUsdtSol from "./MockUsdt.sol";
export type { mockUsdtSol };
export type { OwlToken } from "./OwlToken";
export type { Ownable } from "./Ownable";
export type { Presale } from "./Presale";
