/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as erc20Sol from "./ERC20.sol";
export * as erc20MetaDataSol from "./ERC20MetaData.sol";
export * as mockUsdtSol from "./MockUsdt.sol";
export { OwlToken__factory } from "./OwlToken__factory";
export { Ownable__factory } from "./Ownable__factory";
export { Presale__factory } from "./Presale__factory";
