version: '3.9'

services:
  owlers-service:
    build:
      context: ./owlers-service
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongodb:27017/owlers-db
      - VIRTUAL_HOST=api.owlers.io
      - LETSENCRYPT_HOST=api.owlers.io
      - LETSENCRYPT_EMAIL=your@email.com
    expose:
      - "3000"
    networks:
      - web
      - app-network
    depends_on:
      - mongodb
    restart: always

  owlers-dashboard:
    build:
      context: ./owlers-client
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - VIRTUAL_HOST=dashboard.owlers.io
      - LETSENCRYPT_HOST=dashboard.owlers.io
      - LETSENCRYPT_EMAIL=your@email.com
    expose:
      - "80"
    networks:
      - web
      - app-network
    depends_on:
      - owlers-service
    restart: always

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network
    restart: always

volumes:
  mongodb_data:

networks:
  web:
    external: true
  app-network:
